---

- name: Configure minio connection alias
  command: "mc --insecure alias set local {{ minio_url }} {{ minio_root_user }} {{ minio_root_password }}"

- include_tasks: create_minio_user.yml
  with_items:
    - "{{ minio_users }}"
  loop_control:
    loop_var: "user"

- include_tasks: create_minio_buckets.yml
  args:
    apply:
      delegate_to: localhost
      become: false
