---

- name: Create users
  command: "mc --insecure admin user add local {{ user.name }} {{ user.password }}"

- name: Create users policy file
  template:
    src: minio_policy.json.j2
    dest: "{{ minio_policy_dir }}/{{ user.name }}.json"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0640
  register: create_policy

- name: Add user policy
  command: "{{ mc_command }} admin policy add local {{ user.name }} {{ minio_policy_dir }}/{{ user.name }}.json"
  when: create_policy.changed

- name: Apply user policy
  command: "{{ mc_command }} admin policy set local {{ user.name }} user={{ user.name }}"
  when: create_policy.changed
