---

- name: "This should create a bucket"
  minio_bucket:
    s3_url: "{{ minio_url }}"
    name: "{{ bucket.name }}"
    access_key: "{{ minio_root_user }}"
    secret_key: "{{ minio_root_password }}"
    state: present
    policy: "{{ bucket.policy }}"
    validate_certs: false
