---

- name: Create Minio group
  group:
    name: "{{ minio_group }}"
    state: present
  when: minio_group != "root"

- name: Create Minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: "yes"
    shell: "/usr/sbin/nologin"
  when: minio_group != "root"

- name: Create the Minio config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0750
  with_items:
    - "{{ minio_etc_dir }}"
    - "{{ minio_policy_dir }}"

- name: Create the Minio data storage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0777
  when: minio_server_make_datadirs
  with_items: "{{ minio_server_datadirs }}"

- name: Deploy stack from base compose file and override the web service
  community.docker.docker_stack:
    state: present
    name: "{{ minio_swarm_stack }}"
    compose:
      - version: '3.9'
        services:
          minio0:
            image: "docker.io/bitnami/minio:2024"
            environment:
              MINIO_ROOT_USER: "{{ minio_root_user }}"
              MINIO_ROOT_PASSWORD: "{{ minio_root_password }}"
            deploy:
              restart_policy:
                condition: any
                delay: 30s #time to wait between restart attempts
                max_attempts: 10
                window: 10s #time to wait before deciding if a restart has succeeded
              mode: replicated
              replicas: 1
              update_config:
                monitor: 1m
                failure_action: rollback
              rollback_config:
                delay: 10s
            volumes:
              - /var/lib/minio:/data
            hostname: "{{ minio_swarm_project }}-server1"
            ports:
              - 9001:9001
              - 9000:9000
  register: result_container_start
