---
# Install Minio Server
- name: Install server
  include_tasks: install_server.yml
  when: minio_install_server

# Install Minio Client
- name: Install client
  include_tasks: install_client.yml
  when: minio_install_client

# Add local minio server to Minio client
- name: Configure server
  include_tasks: configure_server.yml
  when: minio_url|length > 0 and minio_install_client
