---
- include_tasks: install_server.yml
  when: minio_install_server

- include_tasks: install_client.yml
  when: minio_install_client

- include_tasks: configure_client.yml
  when: minio_install_server and minio_install_client
