---
# Install Minio Client
- name: Install server
  include_tasks: install_server.yml
  when: minio_install_server

- name: Waiting for start minio
  ansible.builtin.wait_for:
    port: "{{ minio_server_port }}"
    host: "{{ minio_server_addr }}"
    delay: 5
  when: result_container_start is changed

- name: Install client
  include_tasks: install_client.yml
  when: minio_install_client

# Configure server/cluster
- name: Configure server
  include_tasks: configure_server.yml
  when: minio_url|length > 0 and minio_install_client
  # run once per cluster
  run_once: true
