---
# Install Minio Server
- include_tasks: install_server.yml
  when: minio_install_server

# Install Minio Client
- include_tasks: install_client.yml
  when: minio_install_client

# Add local minio server to Minio client
- include_tasks: configure_server.yml
  when: minio_url|length > 0 and minio_install_client
