---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    server_hostname: minio.picluster.ricsanfre.com
    ssl_key_size: 4096
    ssl_certificate_provider: selfsigned

  pre_tasks:
    - name: Generate self-signed SSL certificates for minio
      include_tasks: generate_selfsigned_cert.yml
      args:
        apply:
          delegate_to: localhost
          become: false

  roles:
    - role: ricsanfre.minio
      minio_root_user: "miniadmin"
      minio_root_password: "supers1cret0"
      minio_enable_tls: true
      minio_buckets:
        - name: bucket1
          policy: read-write
      minio_users:
        - name: user1
          password: supers1cret0
